### PR TITLE
Support for ~/.ssh/config to use the ProxyPass options in there

### PR DESCRIPTION
**Pull request by sergiorua**
I don't have direct access to the FortiGate. My connections go via a jump server which I can proxy using ProxyPass on my ~/.ssh/config

I'm using this configuration successfully.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Hello Sergio,
thanks for your pull request. I think that addition is quite interesting and useful. Would you mind adding a quick `rst` file in the docs explaining how to use it? Just a quick example. Once that is done I will merge the PR and build a new version with your addition.

Regards.
David

**Comment by sergiorua** [comment]
rst file added as well as better support for more than just the proxycommand.

**Comment by dbarrosop** [comment]
Great!  Thanks again for the PR : )

+1

**Comment by dbarrosop** [comment]
This has been merged and version 0.46 has been released.

**Pull request merged**
