### PR TITLE
Fix some Python3 issues

### PR DESCRIPTION
**Pull request by ktbyers**
Also some pylint cleanup (which makes it easier to see errors/issues).

### CODE REVIEW

**Comment by ebeahan** [comment]
@StefanLindblom any chance you'd be able to merge this one in and cut a new release on pypi? This resolves a couple of Python3-related issues we ran into on the latest pyFG release. We've done quite a bit of testing with this PR and Python3; should be the last update we need to support Python3 in our napalm-fortios project.

**Comment by ktbyers** [comment]
Yes, would be good to get this released. I think this is pretty much the last thing we need to do to be fully Python3 supported for NAPALM.

**Comment by dbarrosop** [comment]
@StefanLindblom bump

**Comment by mirceaulinic** [comment]
@StefanLindblom or anyone else: is this project still maintained, or should we consider it abandoned by Spotify? I understand issues may take very long to be solved, but at least reviewing a Pull Request should be doable within 24 days. @ktbyers has been kind enough and increased even the version number for you.
If that become too challenging, you are welcome to transfer the repository under the napalm-automation community.

**Comment by StefanLindblom** [comment]
I'm very sorry for the delay here.
This has also drowned in other github notifications on my end.

I'm releasing a new version now.

**Comment by ktbyers** [comment]
@StefanLindblom Thanks for your help on this.

**Pull request merged**
