### PR TITLE
Adding py3 support and some pylama cleanup

### PR DESCRIPTION
**Pull request by ktbyers**
Needed so that napalm-fortios can add Python3 support.

### CODE REVIEW

**Comment by StefanLindblom** [comment]
Thank you for this addition @ktbyers ! Tested using Python 2.7.10 (with which I've been using pyFG prior to these changes)

**Comment by ktbyers** [comment]
Thanks @StefanLindblom. Any possibility we can make a pyFG release and get it up to pypi? 

This will let me use the new pyFG code in the napalm-fortios driver.

**Comment by StefanLindblom** [comment]
All should now be done, uploaded to pypi!

**Comment by ktbyers** [comment]
Thanks @StefanLindblom

**Pull request merged**
